version: '3.3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly yes
      - --appendfsync everysec
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  shop:
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis

volumes:
  redis_data:
  postgres_data:
